import os
# fix_extras.py
# Run this to create extras.py

lines = []
lines.append('# extras.py')
lines.append('# Extra daily content: History, Vocabulary, GK, Countdown, ELI5, Comparisons')
lines.append('')
lines.append('import random')
lines.append('from datetime import datetime, date')
lines.append('from ai_engine import ai')
lines.append('from config.logger import setup_logger')
lines.append('')
lines.append('logger = setup_logger("extras")')
lines.append('')
lines.append('EXAM_DATES = {')
lines.append('    "UPSC Prelims 2025": "2025-05-25",')
lines.append('    "UPSC Mains 2025": "2025-09-19",')
lines.append('    "SSC CGL 2025": "2025-06-15",')
lines.append('    "KPSC KAS Prelims 2025": "2025-06-22",')
lines.append('    "KPSC FDA/SDA 2025": "2025-07-20",')
lines.append('    "RBI Grade B 2025": "2025-08-10",')
lines.append('    "IBPS PO 2025": "2025-10-04",')
lines.append('}')
lines.append('')
lines.append('STRATEGY_TIPS = [')
lines.append('    "Revise current affairs from the last 12 months. Focus on government schemes and international summits.",')
lines.append('    "Solve at least 50 MCQs daily from previous year papers. Analyze why you got wrong answers.",')
lines.append('    "Make short notes of today\'s news. Use keywords, not full sentences. Review them weekly.",')
lines.append('    "Focus on NCERT books for static GK. Class 6-12 covers 60% of Prelims syllabus.",')
lines.append('    "Practice answer writing for 30 minutes daily. Even bullet points help build the habit.",')
lines.append('    "Read one editorial from The Hindu or Indian Express daily. Note 3 key arguments.",')
lines.append('    "Revise one subject\'s static portion today. Rotate subjects through the week.",')
lines.append('    "Attempt a full-length mock test this weekend. Analyze mistakes more than score.",')
lines.append('    "Map-based questions are increasing. Practice marking rivers, national parks on a blank map.",')
lines.append('    "Focus on linking current affairs with static GK. Examiners love connected questions.",')
lines.append('    "Create mnemonics for lists (Articles, Amendments, Committees). They save time in exam.",')
lines.append('    "Revise Government Schemes: name, ministry, launch year, target beneficiaries.",')
lines.append('    "Practice reading comprehension passages. Time yourself: 8 minutes per passage max.",')
lines.append('    "Study constitutional amendments from last 5 years. They are exam favorites.",')
lines.append('    "Review India\'s bilateral relations with neighboring countries. Focus on recent summits.",')
lines.append('    "Mental health matters. Take a 30-minute break. A fresh mind learns better.",')
lines.append(']')
lines.append('')
lines.append('ELI5_TOPICS = [')
lines.append('    "What is Repo Rate and how does it affect common people",')
lines.append('    "What is GDP and how is it calculated",')
lines.append('    "What is Fiscal Deficit and why it matters",')
lines.append('    "How does the GST system work in India",')
lines.append('    "What is the difference between Lok Sabha and Rajya Sabha",')
lines.append('    "What is a Money Bill vs Ordinary Bill",')
lines.append('    "How does the Election Commission conduct elections",')
lines.append('    "What is the role of the CAG",')
lines.append('    "What is the difference between Fundamental Rights and DPSP",')
lines.append('    "How does the Supreme Court work: PIL, Appellate, Advisory",')
lines.append('    "What is Article 370 and what changed",')
lines.append('    "How does RBI control inflation",')
lines.append('    "What is the difference between FDI and FII",')
lines.append('    "What is the Paris Agreement on climate change",')
lines.append('    "What is QUAD and why is it important for India",')
lines.append('    "What is Digital Rupee (CBDC) and how it works",')
lines.append('    "How does Panchayati Raj system work (3 tiers)",')
lines.append('    "What is Anti-Defection Law (10th Schedule)",')
lines.append('    "What is NITI Aayog and how it replaced Planning Commission",')
lines.append('    "What is the Nuclear Triad and India\'s nuclear doctrine",')
lines.append(']')
lines.append('')
lines.append('COMPARISON_TOPICS = [')
lines.append('    "Fundamental Rights vs Directive Principles of State Policy",')
lines.append('    "Lok Sabha vs Rajya Sabha",')
lines.append('    "Governor vs President of India",')
lines.append('    "Money Bill vs Ordinary Bill vs Finance Bill",')
lines.append('    "National Park vs Wildlife Sanctuary vs Biosphere Reserve",')
lines.append('    "FDI vs FII vs FPI",')
lines.append('    "Fiscal Policy vs Monetary Policy",')
lines.append('    "NITI Aayog vs Planning Commission",')
lines.append('    "Parliamentary vs Presidential system",')
lines.append('    "Supreme Court vs High Court jurisdiction",')
lines.append('    "Censure Motion vs No Confidence Motion",')
lines.append('    "Emergency under Article 352 vs 356 vs 360",')
lines.append('    "Revenue Expenditure vs Capital Expenditure",')
lines.append('    "CBI vs NIA vs ED: roles and differences",')
lines.append('    "Tropical Evergreen Forest vs Tropical Deciduous Forest",')
lines.append(']')
lines.append('')
lines.append('')
lines.append('class ExtraContent:')
lines.append('')
lines.append('    def __init__(self):')
lines.append('        self.today = datetime.now()')
lines.append('        self.day = self.today.day')
lines.append('        self.month = self.today.strftime("%B")')
lines.append('        self.date_nice = self.today.strftime("%d %B %Y")')
lines.append('        self.day_name = self.today.strftime("%A")')
lines.append('        self.day_of_week = self.today.weekday()')
lines.append('')
lines.append('    def this_day_in_history(self):')
lines.append('        logger.info("Generating This Day in History...")')
lines.append('        prompt = f"List 5 important historical events that happened on {self.day} {self.month} (any year). Include 2-3 events related to India and 2-3 international events. Focus on events asked in UPSC/SSC exams. FORMAT: YEAR - Event description in 1 clear line. After the 5 events add: EXAM TIP: Which event is most frequently asked and why (1 line). Plain text only."')
lines.append('        content = ai.query(prompt, temperature=0.3, max_tokens=400)')
lines.append('        if not content:')
lines.append('            return None')
lines.append('        post = f"""📜  <b>THIS DAY IN HISTORY</b>')
lines.append('📅  <b>{self.date_nice}</b>')
lines.append('━━━━━━━━━━━━━━━━━━━━━━━━━━━')
lines.append('')
lines.append('{content}')
lines.append('')
lines.append('━━━━━━━━━━━━━━━━━━━━━━━━━━━')
lines.append('💡 <i>History repeats in exams. Learn from it!</i>')
lines.append('━━━━━━━━━━━━━━━━━━━━━━━━━━━')
lines.append('#ThisDayInHistory #UPSC #GovtExams"""')
lines.append('        return post')
lines.append('')
lines.append('    def vocabulary_word(self):')
lines.append('        logger.info("Generating Word of the Day...")')
lines.append('        prompt = "Pick ONE advanced English vocabulary word useful for government exams. Provide: WORD (in capitals), PRONUNCIATION, TYPE (noun/verb/adj), MEANING (1 line), EXAMPLE (sentence about government/policy), SYNONYMS (3 words), ANTONYMS (2 words), MEMORY TIP (creative trick to remember, 1 line). Plain text only."')
lines.append('        content = ai.query(prompt, temperature=0.5, max_tokens=300)')
lines.append('        if not content:')
lines.append('            return None')
lines.append('        post = f"""📖  <b>WORD OF THE DAY</b>')
lines.append('📅  <b>{self.date_nice}</b>')
lines.append('━━━━━━━━━━━━━━━━━━━━━━━━━━━')
lines.append('')
lines.append('{content}')
lines.append('')
lines.append('━━━━━━━━━━━━━━━━━━━━━━━━━━━')
lines.append('💡 <i>1 word/day = 365 new words/year!</i>')
lines.append('━━━━━━━━━━━━━━━━━━━━━━━━━━━')
lines.append('#WordOfTheDay #Vocabulary #English"""')
lines.append('        return post')
lines.append('')
lines.append('    def daily_static_gk(self):')
lines.append('        logger.info("Generating GK Capsule...")')
lines.append('        topics = [')
lines.append('            "an important Article of Indian Constitution",')
lines.append('            "a Constitutional Amendment of India",')
lines.append('            "a Constitutional Body of India",')
lines.append('            "an important International Organization",')
lines.append('            "a National Park or Tiger Reserve of India",')
lines.append('            "an important river system of India",')
lines.append('            "an Indian Space Mission (ISRO)",')
lines.append('            "a Social Reformer of India",')
lines.append('            "a UNESCO World Heritage Site in India",')
lines.append('            "a classical dance form of India",')
lines.append('            "a Ramsar Wetland Site of India",')
lines.append('            "a GI Tag product of India",')
lines.append('            "a Biosphere Reserve of India",')
lines.append('            "a Schedule of the Indian Constitution",')
lines.append('        ]')
lines.append('        topic = random.choice(topics)')
lines.append('        prompt = f"Create a short exam-focused fact capsule about {topic}. Choose a specific example. Give: TOPIC (specific name), CATEGORY, KEY FACTS (5 facts with dates/numbers), WHY IMPORTANT FOR EXAMS (1 line), EXAM HISTORY (has this been asked? which exam?). Plain text only."')
lines.append('        content = ai.query(prompt, temperature=0.4, max_tokens=350)')
lines.append('        if not content:')
lines.append('            return None')
lines.append('        post = f"""💡  <b>DAILY GK CAPSULE</b>')
lines.append('📅  <b>{self.date_nice}</b>')
lines.append('━━━━━━━━━━━━━━━━━━━━━━━━━━━')
lines.append('')
lines.append('{content}')
lines.append('')
lines.append('━━━━━━━━━━━━━━━━━━━━━━━━━━━')
lines.append('📌 <i>Save this for revision!</i>')
lines.append('━━━━━━━━━━━━━━━━━━━━━━━━━━━')
lines.append('#StaticGK #GKCapsule #UPSC #SSC"""')
lines.append('        return post')
lines.append('')
lines.append('    def prelims_countdown(self):')
lines.append('        logger.info("Generating Exam Countdown...")')
lines.append('        today_date = date.today()')
lines.append('        tip = random.choice(STRATEGY_TIPS)')
lines.append('        countdown_lines = []')
lines.append('        for exam_name, exam_date_str in EXAM_DATES.items():')
lines.append('            try:')
lines.append('                exam_date = datetime.strptime(exam_date_str, "%Y-%m-%d").date()')
lines.append('                days_left = (exam_date - today_date).days')
lines.append('                if days_left > 0:')
lines.append('                    if days_left <= 30:')
lines.append('                        icon = "🔴"')
lines.append('                    elif days_left <= 90:')
lines.append('                        icon = "🟡"')
lines.append('                    else:')
lines.append('                        icon = "🟢"')
lines.append('                    countdown_lines.append(f"  {icon} <b>{exam_name}</b>")')
lines.append('                    countdown_lines.append(f"     📅 {exam_date.strftime(chr(37)+chr(100)+chr(32)+chr(37)+chr(66)+chr(32)+chr(37)+chr(89))} — <b>{days_left} days left</b>")')
lines.append('                    countdown_lines.append("")')
lines.append('            except:')
lines.append('                pass')
lines.append('        if not countdown_lines:')
lines.append('            countdown_lines = ["  Exam dates will be updated soon!"]')
lines.append('        countdown_text = chr(10).join(countdown_lines)')
lines.append('        post = f"""⏰  <b>EXAM COUNTDOWN</b>')
lines.append('📅  <b>{self.date_nice}</b>')
lines.append('━━━━━━━━━━━━━━━━━━━━━━━━━━━')
lines.append('')
lines.append('{countdown_text}')
lines.append('')
lines.append('━━━━━━━━━━━━━━━━━━━━━━━━━━━')
lines.append('')
lines.append('🎯 <b>Today\'s Strategy Tip:</b>')
lines.append('<i>{tip}</i>')
lines.append('')
lines.append('━━━━━━━━━━━━━━━━━━━━━━━━━━━')
lines.append('')
lines.append('📋 <b>Daily Checklist:</b>')
lines.append('  ☐ Read today\'s current affairs')
lines.append('  ☐ Attempt today\'s quiz')
lines.append('  ☐ Revise 1 static GK topic')
lines.append('  ☐ Solve 30 previous year MCQs')
lines.append('  ☐ Read 1 editorial')
lines.append('')
lines.append('━━━━━━━━━━━━━━━━━━━━━━━━━━━')
lines.append('#ExamCountdown #UPSC #Motivation"""')
lines.append('        return post')
lines.append('')
lines.append('    def eli5_post(self):')
lines.append('        logger.info("Generating ELI5 post...")')
lines.append('        topic = random.choice(ELI5_TOPICS)')
lines.append('        prompt = f"Explain this topic in very simple language: {topic}. Rules: 1) Use a simple real-life analogy first 2) Then explain the actual concept 3) Give 3-4 key points in simple language 4) End with why this matters for exams 5) Maximum 150 words 6) No jargon 7) Plain text only."')
lines.append('        content = ai.query(prompt, temperature=0.4, max_tokens=400)')
lines.append('        if not content:')
lines.append('            return None')
lines.append('        post = f"""🎯  <b>CONCEPT SIMPLIFIED</b>')
lines.append('📅  <b>{self.date_nice}</b>')
lines.append('━━━━━━━━━━━━━━━━━━━━━━━━━━━')
lines.append('')
lines.append('📌 <b>Topic: {topic}</b>')
lines.append('')
lines.append('━━━━━━━━━━━━━━━━━━━━━━━━━━━')
lines.append('')
lines.append('{content}')
lines.append('')
lines.append('━━━━━━━━━━━━━━━━━━━━━━━━━━━')
lines.append('💡 <i>Complex topic? We simplify it daily!</i>')
lines.append('━━━━━━━━━━━━━━━━━━━━━━━━━━━')
lines.append('#ConceptSimplified #ELI5 #UPSC"""')
lines.append('        return post')
lines.append('')
lines.append('    def comparison_table(self):')
lines.append('        logger.info("Generating Comparison Table...")')
lines.append('        topic = random.choice(COMPARISON_TOPICS)')
lines.append('        prompt = f"Create a comparison between: {topic}. Compare on 5 points. For each point give the answer for both items. FORMAT: ITEM 1: (name), ITEM 2: (name), then Point 1: aspect - Item1: answer vs Item2: answer (repeat for 5 points). End with KEY EXAM POINT: what examiners usually ask (1 line). Plain text only."')
lines.append('        content = ai.query(prompt, temperature=0.3, max_tokens=500)')
lines.append('        if not content:')
lines.append('            return None')
lines.append('        post = f"""📊  <b>COMPARE AND LEARN</b>')
lines.append('📅  <b>{self.date_nice}</b>')
lines.append('━━━━━━━━━━━━━━━━━━━━━━━━━━━')
lines.append('')
lines.append('📌 <b>{topic}</b>')
lines.append('')
lines.append('━━━━━━━━━━━━━━━━━━━━━━━━━━━')
lines.append('')
lines.append('{content}')
lines.append('')
lines.append('━━━━━━━━━━━━━━━━━━━━━━━━━━━')
lines.append('📌 <i>Save this table for quick revision!</i>')
lines.append('━━━━━━━━━━━━━━━━━━━━━━━━━━━')
lines.append('#CompareAndLearn #UPSC #QuickRevision"""')
lines.append('        return post')
lines.append('')
lines.append('    def weekly_summary(self):')
lines.append('        if self.day_of_week != 6:')
lines.append('            return None')
lines.append('        logger.info("Generating Weekly Summary...")')
lines.append('        prompt = "Create a weekly current affairs summary for UPSC aspirants. List the top 8 most important news from India and world this week. For each: 1 line headline, 1 line exam importance, category (Economy/Polity/IR/Science/Environment/Defense/Schemes). Focus on exam-relevant news. Plain text only."')
lines.append('        content = ai.query(prompt, temperature=0.3, max_tokens=600)')
lines.append('        if not content:')
lines.append('            return None')
lines.append('        post = f"""📚  <b>WEEKLY NEWS RECAP</b>')
lines.append('📅  <b>Week ending {self.date_nice}</b>')
lines.append('━━━━━━━━━━━━━━━━━━━━━━━━━━━')
lines.append('')
lines.append('{content}')
lines.append('')
lines.append('━━━━━━━━━━━━━━━━━━━━━━━━━━━')
lines.append('📌 <i>Revise this every Sunday for Prelims!</i>')
lines.append('━━━━━━━━━━━━━━━━━━━━━━━━━━━')
lines.append('#WeeklyRevision #SundayRevision #CurrentAffairs"""')
lines.append('        return post')
lines.append('')
lines.append('    def get_todays_extras(self):')
lines.append('        posts = []')
lines.append('        history = self.this_day_in_history()')
lines.append('        if history:')
lines.append('            posts.append(("This Day in History", history))')
lines.append('        vocab = self.vocabulary_word()')
lines.append('        if vocab:')
lines.append('            posts.append(("Word of the Day", vocab))')
lines.append('        countdown = self.prelims_countdown()')
lines.append('        if countdown:')
lines.append('            posts.append(("Exam Countdown", countdown))')
lines.append('        day = self.day_of_week')
lines.append('        if day in [0, 3, 6]:')
lines.append('            gk = self.daily_static_gk()')
lines.append('            if gk:')
lines.append('                posts.append(("GK Capsule", gk))')
lines.append('        if day in [1, 4]:')
lines.append('            eli5 = self.eli5_post()')
lines.append('            if eli5:')
lines.append('                posts.append(("Concept Simplified", eli5))')
lines.append('        if day in [2, 5]:')
lines.append('            comp = self.comparison_table()')
lines.append('            if comp:')
lines.append('                posts.append(("Compare and Learn", comp))')
lines.append('        if day == 6:')
lines.append('            weekly = self.weekly_summary()')
lines.append('            if weekly:')
lines.append('                posts.append(("Weekly Summary", weekly))')
lines.append('        return posts')
lines.append('')
lines.append('')
lines.append('if __name__ == "__main__":')
lines.append('    print("Testing extras...")')
lines.append('    extra = ExtraContent()')
lines.append('    posts = extra.get_todays_extras()')
lines.append('    print(f"Generated {len(posts)} extra posts for {extra.day_name}")')
lines.append('    for name, post in posts:')
lines.append('        print(f"  - {name}: {len(post)} characters")')

# Write the file
with open('extras.py', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

# Verify
size = os.path.getsize('extras.py')
print(f"Created extras.py — {size} bytes")

# Quick test
try:
    from extras import ExtraContent
    print("Import test: OK")
except Exception as e:
    print(f"Import test FAILED: {e}")