import importlib.util
import os
# fix_main.py
# Run this to create the updated main.py with extras support

code = []
code.append("# main.py")
code.append("")
code.append("import json")
code.append("import os")
code.append("import sys")
code.append("import time")
code.append("import schedule")
code.append("from datetime import datetime, date, timedelta")
code.append("")
code.append("from news_scraper import NewsScraper")
code.append("from news_filter import NewsFilter")
code.append("from content_generator import ContentGenerator")
code.append("from quiz_generator import QuizGenerator")
code.append("from excel_saver import ExcelSaver")
code.append("from telegram_poster import TelegramPoster, run_async")
code.append("from extras import ExtraContent")
code.append("from config.settings import (")
code.append("    MORNING_NEWS_TIME, EVENING_QUIZ_TIME,")
code.append("    FILTERED_NEWS_DIR, DATA_DIR")
code.append(")")
code.append("from config.logger import setup_logger")
code.append("")
code.append("logger = setup_logger('main')")
code.append("")
code.append("STATE_FILE = os.path.join(DATA_DIR, 'job_state.json')")
code.append("IS_GITHUB = os.environ.get('GITHUB_ACTIONS') == 'true'")
code.append("")
code.append("")
code.append("def is_done_today(job_name):")
code.append("    if IS_GITHUB:")
code.append("        return False")
code.append("    try:")
code.append("        if os.path.exists(STATE_FILE):")
code.append("            with open(STATE_FILE, 'r') as f:")
code.append("                state = json.load(f)")
code.append("            today = str(date.today())")
code.append("            return today in state and job_name in state[today]")
code.append("    except:")
code.append("        pass")
code.append("    return False")
code.append("")
code.append("")
code.append("def mark_done(job_name):")
code.append("    if IS_GITHUB:")
code.append("        return")
code.append("    state = {}")
code.append("    try:")
code.append("        if os.path.exists(STATE_FILE):")
code.append("            with open(STATE_FILE, 'r') as f:")
code.append("                state = json.load(f)")
code.append("    except:")
code.append("        pass")
code.append("    today = str(date.today())")
code.append("    if today not in state:")
code.append("        state[today] = {}")
code.append("    state[today][job_name] = datetime.now().strftime('%H:%M:%S')")
code.append("    with open(STATE_FILE, 'w') as f:")
code.append("        json.dump(state, f, indent=2)")
code.append("")
code.append("")
code.append("def morning_news_pipeline():")
code.append("    if is_done_today('morning_news'):")
code.append("        print('Morning news already done today! Skipping.')")
code.append("        return")
code.append("")
code.append("    start = datetime.now()")
code.append("    print('')")
code.append("    print('=' * 55)")
code.append("    print(f'   MORNING NEWS PIPELINE - {start.strftime(\"%H:%M:%S\")}')")
code.append("    print('=' * 55)")
code.append("")
code.append("    from config.settings import BOT_TOKEN, CHANNEL_ID, GEMINI_API_KEY, GROQ_API_KEY")
code.append("    print(f'   Running on: {\"GitHub Actions\" if IS_GITHUB else \"Local PC\"}')")
code.append("    bt = 'YES' if BOT_TOKEN and 'PASTE_' not in BOT_TOKEN and 'YOUR_' not in BOT_TOKEN else 'NO'")
code.append("    gm = 'YES' if GEMINI_API_KEY and 'PASTE_' not in GEMINI_API_KEY and 'YOUR_' not in GEMINI_API_KEY else 'NO'")
code.append("    gr = 'YES' if GROQ_API_KEY and 'PASTE_' not in GROQ_API_KEY and 'YOUR_' not in GROQ_API_KEY else 'NO'")
code.append("    print(f'   BOT_TOKEN: {bt} | CHANNEL: {CHANNEL_ID} | GEMINI: {gm} | GROQ: {gr}')")
code.append("")
code.append("    excel = ExcelSaver()")
code.append("")
code.append("    try:")
code.append("        print('\\n>>> STEP 1: Scraping news...')")
code.append("        scraper = NewsScraper()")
code.append("        raw = scraper.fetch_all_news()")
code.append("        print(f'   Got {len(raw)} articles')")
code.append("        excel.save_scraped_news(raw)")
code.append("")
code.append("        if not raw:")
code.append("            print('   ERROR: No articles found!')")
code.append("            return")
code.append("")
code.append("        print('\\n>>> STEP 2: AI Filtering...')")
code.append("        filterer = NewsFilter()")
code.append("        filtered, stats = filterer.filter_articles(raw)")
code.append("        print(f'   Selected {len(filtered)} relevant articles')")
code.append("        excel.save_filtered_news(filtered, stats)")
code.append("")
code.append("        if not filtered:")
code.append("            print('   WARNING: No relevant articles today!')")
code.append("            return")
code.append("")
code.append("        print('\\n>>> STEP 3: Creating news posts...')")
code.append("        generator = ContentGenerator()")
code.append("        posts, post_data = generator.generate_all_posts(filtered)")
code.append("        print(f'   Created {len(posts)} posts')")
code.append("        excel.save_posts(post_data)")
code.append("")
code.append("        print('\\n>>> STEP 4: Posting news to Telegram...')")
code.append("        poster = TelegramPoster()")
code.append("        ok, fail = run_async(poster.post_news(posts))")
code.append("        print(f'   Results: {ok} sent, {fail} failed')")
code.append("        excel.save_posting_log('Morning News', 'Success', f'Sent:{ok} Failed:{fail}')")
code.append("")
code.append("        print('\\n>>> STEP 5: Posting extra content...')")
code.append("        try:")
code.append("            extra = ExtraContent()")
code.append("            extra_posts = extra.get_todays_extras()")
code.append("            print(f'   Generated {len(extra_posts)} extras for {extra.day_name}')")
code.append("            for name, post_content in extra_posts:")
code.append("                print(f'   Posting: {name}...')")
code.append("                result = run_async(poster.send_text(post_content))")
code.append("                status = 'OK' if result else 'FAILED'")
code.append("                print(f'   {status}: {name}')")
code.append("                time.sleep(3)")
code.append("            excel.save_posting_log('Extra Content', 'Success', f'{len(extra_posts)} extras')")
code.append("        except Exception as e:")
code.append("            print(f'   Extra content error (not critical): {e}')")
code.append("")
code.append("        mark_done('morning_news')")
code.append("        elapsed = (datetime.now() - start).total_seconds()")
code.append("        print(f'\\nDONE in {elapsed:.0f} seconds!')")
code.append("")
code.append("    except Exception as e:")
code.append("        print(f'\\nERROR: {e}')")
code.append("        import traceback")
code.append("        traceback.print_exc()")
code.append("        try:")
code.append("            excel.save_posting_log('Morning News', 'Failed', str(e))")
code.append("        except:")
code.append("            pass")
code.append("")
code.append("")
code.append("def evening_quiz_pipeline():")
code.append("    if is_done_today('evening_quiz'):")
code.append("        print('Evening quiz already done today! Skipping.')")
code.append("        return")
code.append("")
code.append("    start = datetime.now()")
code.append("    print('')")
code.append("    print('=' * 55)")
code.append("    print(f'   EVENING QUIZ PIPELINE - {start.strftime(\"%H:%M:%S\")}')")
code.append("    print('=' * 55)")
code.append("")
code.append("    from config.settings import BOT_TOKEN, CHANNEL_ID")
code.append("    print(f'   Running on: {\"GitHub Actions\" if IS_GITHUB else \"Local PC\"}')")
code.append("    bt = 'YES' if BOT_TOKEN and 'PASTE_' not in BOT_TOKEN and 'YOUR_' not in BOT_TOKEN else 'NO'")
code.append("    print(f'   BOT_TOKEN: {bt} | CHANNEL: {CHANNEL_ID}')")
code.append("")
code.append("    excel = ExcelSaver()")
code.append("    today = datetime.now().strftime('%Y-%m-%d')")
code.append("")
code.append("    try:")
code.append("        print('\\n>>> STEP 1: Loading filtered news...')")
code.append("        filtered_file = os.path.join(FILTERED_NEWS_DIR, f'filtered_{today}.json')")
code.append("        if not os.path.exists(filtered_file):")
code.append("            print('   No filtered file. Running scrape+filter...')")
code.append("            scraper = NewsScraper()")
code.append("            raw = scraper.fetch_all_news()")
code.append("            filterer = NewsFilter()")
code.append("            filtered, stats = filterer.filter_articles(raw)")
code.append("            excel.save_scraped_news(raw)")
code.append("            excel.save_filtered_news(filtered, stats)")
code.append("        else:")
code.append("            with open(filtered_file, 'r', encoding='utf-8') as f:")
code.append("                filtered = json.load(f)")
code.append("        print(f'   Loaded {len(filtered)} articles')")
code.append("")
code.append("        if not filtered:")
code.append("            print('   WARNING: No articles for quiz!')")
code.append("            return")
code.append("")
code.append("        print('\\n>>> STEP 2: Generating quiz questions...')")
code.append("        quiz_gen = QuizGenerator()")
code.append("        questions = quiz_gen.generate_daily_quiz(filtered)")
code.append("        print(f'   Created {len(questions)} questions')")
code.append("        excel.save_quiz(questions)")
code.append("")
code.append("        if not questions:")
code.append("            print('   WARNING: No questions generated!')")
code.append("            return")
code.append("")
code.append("        print('\\n>>> STEP 3: Posting quiz to Telegram...')")
code.append("        quiz_posts = quiz_gen.format_for_telegram(questions)")
code.append("        poster = TelegramPoster()")
code.append("        ok, fail = run_async(poster.post_quiz(quiz_posts))")
code.append("        print(f'   Results: {ok} sent, {fail} failed')")
code.append("        excel.save_posting_log('Evening Quiz', 'Success', f'Q:{len(questions)} Sent:{ok}')")
code.append("")
code.append("        print('\\n>>> STEP 4: Updating master database...')")
code.append("        excel.update_master(filtered, questions)")
code.append("")
code.append("        mark_done('evening_quiz')")
code.append("        elapsed = (datetime.now() - start).total_seconds()")
code.append("        print(f'\\nDONE in {elapsed:.0f} seconds!')")
code.append("")
code.append("    except Exception as e:")
code.append("        print(f'\\nERROR: {e}')")
code.append("        import traceback")
code.append("        traceback.print_exc()")
code.append("        try:")
code.append("            excel.save_posting_log('Evening Quiz', 'Failed', str(e))")
code.append("        except:")
code.append("            pass")
code.append("")
code.append("")
code.append("def check_missed_jobs():")
code.append("    now = datetime.now()")
code.append("    hour = now.hour")
code.append("    morning_hour = int(MORNING_NEWS_TIME.split(':')[0])")
code.append("    evening_hour = int(EVENING_QUIZ_TIME.split(':')[0])")
code.append("    print(f'Checking missed jobs (time: {now.strftime(\"%H:%M\")})...')")
code.append("    if hour >= morning_hour and not is_done_today('morning_news'):")
code.append("        print('   Morning news MISSED - running now!')")
code.append("        morning_news_pipeline()")
code.append("    elif is_done_today('morning_news'):")
code.append("        print('   Morning news: Done today')")
code.append("    else:")
code.append("        print(f'   Morning news: Scheduled at {MORNING_NEWS_TIME}')")
code.append("    if hour >= evening_hour and not is_done_today('evening_quiz'):")
code.append("        print('   Evening quiz MISSED - running now!')")
code.append("        evening_quiz_pipeline()")
code.append("    elif is_done_today('evening_quiz'):")
code.append("        print('   Evening quiz: Done today')")
code.append("    else:")
code.append("        print(f'   Evening quiz: Scheduled at {EVENING_QUIZ_TIME}')")
code.append("")
code.append("")
code.append("def start():")
code.append("    print('')")
code.append("    print('=' * 55)")
code.append("    print('   GOVT EXAM NEWS BOT - ALL FEATURES')")
code.append("    print('=' * 55)")
code.append("    print(f'   News + Extras: {MORNING_NEWS_TIME}')")
code.append("    print(f'   Quiz:          {EVENING_QUIZ_TIME}')")
code.append("    print('=' * 55)")
code.append("    check_missed_jobs()")
code.append("    schedule.every().day.at(MORNING_NEWS_TIME).do(morning_news_pipeline)")
code.append("    schedule.every().day.at(EVENING_QUIZ_TIME).do(evening_quiz_pipeline)")
code.append("    print('\\n   Running. Press Ctrl+C to stop.\\n')")
code.append("    while True:")
code.append("        schedule.run_pending()")
code.append("        time.sleep(30)")
code.append("")
code.append("")
code.append("if __name__ == '__main__':")
code.append("    command = sys.argv[1] if len(sys.argv) > 1 else 'start'")
code.append("    if command == 'test':")
code.append("        print('FULL TEST...')")
code.append("        morning_news_pipeline()")
code.append("        print('\\nMorning done! Quiz in 10 seconds...\\n')")
code.append("        time.sleep(10)")
code.append("        evening_quiz_pipeline()")
code.append("        print('\\nCOMPLETE!')")
code.append("    elif command == 'news':")
code.append("        morning_news_pipeline()")
code.append("    elif command == 'quiz':")
code.append("        evening_quiz_pipeline()")
code.append("    elif command == 'extras':")
code.append("        print('Testing extra content only...')")
code.append("        poster = TelegramPoster()")
code.append("        extra = ExtraContent()")
code.append("        extra_posts = extra.get_todays_extras()")
code.append("        print(f'Generated {len(extra_posts)} posts')")
code.append("        for name, content in extra_posts:")
code.append("            print(f'Posting: {name}...')")
code.append("            run_async(poster.send_text(content))")
code.append("            time.sleep(3)")
code.append("        print('Done!')")
code.append("    elif command == 'start':")
code.append("        start()")
code.append("    elif command == 'status':")
code.append("        today_str = str(date.today())")
code.append("        print(f'\\nStatus for {today_str}:')")
code.append("        if os.path.exists(STATE_FILE):")
code.append("            with open(STATE_FILE, 'r') as f:")
code.append("                state = json.load(f)")
code.append("            if today_str in state:")
code.append("                for job, t in state[today_str].items():")
code.append("                    print(f'   Done: {job} at {t}')")
code.append("            else:")
code.append("                print('   No jobs done today')")
code.append("        else:")
code.append("            print('   No history')")
code.append("    elif command == 'reset':")
code.append("        if os.path.exists(STATE_FILE):")
code.append("            os.remove(STATE_FILE)")
code.append("            print('State reset!')")
code.append("        else:")
code.append("            print('No state file found.')")
code.append("    else:")
code.append("        print('Usage: python main.py [test|news|quiz|extras|start|status|reset]')")

with open('main.py', 'w', encoding='utf-8') as f:
    f.write('\n'.join(code))

size = os.path.getsize('main.py')
print(f"Created main.py — {size} bytes")

try:
    import importlib
    spec = importlib.util.spec_from_file_location("main", "main.py")
    print("Syntax check: OK")
except Exception as e:
    print(f"Syntax check: {e}")